export const FETCH_BRAND_REQUESTED = 'FETCH_BRAND_REQUESTED';
export const FETCH_BRAND_SUCCEED = 'FETCH_BRAND_SUCCEED';
export const FETCH_BRAND_FAILED = 'FETCH_BRAND_FAILED';
export const FETCH_BRAND_RESETED = 'FETCH_BRAND_RESETED';
