export const FETCH_CART_REQUESTED = 'FETCH_CART_REQUESTED';
export const FETCH_CART_SUCCEED = 'FETCH_CART_SUCCEED';
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED';
export const FETCH_CART_RESETED = 'FETCH_CART_RESETED';

export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_SUCCEED = 'ADD_TO_CART_SUCCEED';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';
export const ADD_TO_CART_RESETED = 'ADD_TO_CART_RESETED';

export const DELETE_CART_ITEM_REQUESTED = 'DELETE_CART_ITEM_REQUESTED';
export const DELETE_CART_ITEM_SUCCEED = 'DELETE_CART_ITEM_SUCCEED';
export const DELETE_CART_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED';
export const DELETE_CART_ITEM_RESETED = 'DELETE_CART_ITEM_RESETED';

export const CHECKOUT_REQUESTED = 'CHECKOUT_REQUESTED';
export const CHECKOUT_SUCCEED = 'CHECKOUT_SUCCEED';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';
export const CHECKOUT_RESETED = 'CHECKOUT_RESETED';
