export const FETCH_CATEGORY_REQUESTED = 'FETCH_CATEGORY_REQUESTED';
export const FETCH_CATEGORY_SUCCEED = 'FETCH_CATEGORY_SUCCEED';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FETCH_CATEGORY_RESETED = 'FETCH_CATEGORY_RESETED';

export const SINGLE_CATEGORY_REQUESTED = 'SINGLE_CATEGORY_REQUESTED';
export const SINGLE_CATEGORY_SUCCEED = 'SINGLE_CATEGORY_SUCCEED';
export const SINGLE_CATEGORY_FAILED = 'SINGLE_CATEGORY_FAILED';
export const SINGLE_CATEGORY_RESETED = 'SINGLE_CATEGORY_RESETED';
