export const FETCH_NEW_PRODUCT_REQUESTED = 'FETCH_NEW_PRODUCT_REQUESTED';
export const FETCH_NEW_PRODUCT_SUCCEED = 'FETCH_NEW_PRODUCT_SUCCEED';
export const FETCH_NEW_PRODUCT_FAILED = 'FETCH_NEW_PRODUCT_FAILED';
export const FETCH_NEW_PRODUCT_RESETED = 'FETCH_NEW_PRODUCT_RESETED';

export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
export const SORT_BY_TITLE_POST_SUCCEED = 'SORT_BY_TITLE_POST_SUCCEED';
export const SORT_BY_CREATED_AT_POST_SUCCEED = 'SORT_BY_CREATED_AT_POST_SUCCEED';
export const FILTER_BY_VALUE_POST_SUCCEED = 'FILTER_BY_VALUE_POST_SUCCEED';
export const FETCH_NEW_PAGE_POST_SUCCEED = 'FETCH_NEW_PAGE_POST_SUCCEED';
export const FETCH_EXACT_PAGE_POST_SUCCEED = 'FETCH_EXACT_PAGE_POST_SUCCEED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';
export const FETCH_POST_RESETED = 'FETCH_POST_RESETED';

export const SINGLE_PRODUCT_REQUESTED = 'SINGLE_PRODUCT_REQUESTED';
export const SINGLE_PRODUCT_SUCCEED = 'SINGLE_PRODUCT_SUCCEED';
export const SINGLE_PRODUCT_FAILED = 'SINGLE_PRODUCT_FAILED';
export const SINGLE_PRODUCT_RESETED = 'SINGLE_PRODUCT_RESETED';

export const RELATED_PRODUCT_REQUESTED = 'RELATED_PRODUCT_REQUESTED';
export const RELATED_PRODUCT_SUCCEED = 'RELATED_PRODUCT_SUCCEED';
export const RELATED_PRODUCT_FAILED = 'RELATED_PRODUCT_FAILED';
export const RELATED_PRODUCT_RESETED = 'RELATED_PRODUCT_RESETED';

export const FILTER_PRODUCT_REQUESTED = 'FILTER_PRODUCT_REQUESTED';
export const FILTER_PRODUCT_SUCCEED = 'FILTER_PRODUCT_SUCCEED';
export const FILTER_PRODUCT_BY_VALUE_SUCCEED = 'FILTER_PRODUCT_BY_VALUE_SUCCEED';
export const FILTER_MORE_PRODUCT_REQUESTED = 'FILTER_MORE_PRODUCT_REQUESTED';
export const FILTER_MORE_PRODUCT_SUCCEED = 'FILTER_MORE_PRODUCT_SUCCEED';
export const FILTER_PRODUCT_FAILED = 'FILTER_PRODUCT_FAILED';
export const FILTER_PRODUCT_RESETED = 'FILTER_PRODUCT_RESETED';
